### PR TITLE
Ca 10 tag based authorization

### PR DESCRIPTION
**Pull request by fvazquez-caylent**
To allow having a consistency across modules we performed the following.

Summary of changes:

Updates tags var description.
Create Examples/Minimal with exampled tags.

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
Great update to the example and making the description for tags consistent across all of the modules!

I agree that this is not a significant enough change to warrant a version bump.

**Pull request merged**
